DOMAIN_PREFIX = 'luxpower'
DOMAIN = 'luxpower'

# Config UI Attributes
ATTR_LUX_HOST = "lux_host"
ATTR_LUX_PORT = "lux_port"
ATTR_LUX_DONGLE_SERIAL = "lux_dongle_serial"
ATTR_LUX_SERIAL_NUMBER = "lux_serial_number"

# Placeholder values
PLACEHOLDER_LUX_HOST = "127.0.0.1"
PLACEHOLDER_LUX_PORT = 8000
PLACEHOLDER_LUX_DONGLE_SERIAL = "BA19520393"
PLACEHOLDER_LUX_SERIAL_NUMBER = "0102005050"

