from .const import EVENT_DATA_FORMAT, EVENT_DATA_BANK0_FORMAT, EVENT_DATA_BANK1_FORMAT, EVENT_DATA_BANK2_FORMAT, \
                   EVENT_REGISTER_FORMAT, EVENT_REGISTER_21_FORMAT, \
                   EVENT_REGISTER_BANK0_FORMAT, EVENT_REGISTER_BANK1_FORMAT, EVENT_REGISTER_BANK2_FORMAT, EVENT_REGISTER_BANK3_FORMAT, EVENT_REGISTER_BANK4_FORMAT, \
                   CLIENT_DAEMON_FORMAT, DOMAIN


class Event:
    def __init__(self, dongle) -> None:
        self.INVERTER_ID = dongle
        self.EVENT_DATA_RECEIVED = EVENT_DATA_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_DATA_BANK0_RECEIVED = EVENT_DATA_BANK0_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_DATA_BANK1_RECEIVED = EVENT_DATA_BANK1_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_DATA_BANK2_RECEIVED = EVENT_DATA_BANK2_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_REGISTER_RECEIVED = EVENT_REGISTER_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_REGISTER_21_RECEIVED = EVENT_REGISTER_21_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_REGISTER_BANK0_RECEIVED = EVENT_REGISTER_BANK0_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_REGISTER_BANK1_RECEIVED = EVENT_REGISTER_BANK1_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_REGISTER_BANK2_RECEIVED = EVENT_REGISTER_BANK2_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_REGISTER_BANK3_RECEIVED = EVENT_REGISTER_BANK3_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.EVENT_REGISTER_BANK4_RECEIVED = EVENT_REGISTER_BANK4_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)
        self.CLIENT_DAEMON = CLIENT_DAEMON_FORMAT.format(DOMAIN=DOMAIN, DONGLE=self.INVERTER_ID)


